### PR TITLE
Improve struct defaults

### PR DESCRIPTION
**Pull request by ulissesalmeida**
The recommended option is to use the `new`
constructor, however, it doesn't mean we couldn't
have a better default for structs.

Let's say a has a repeated field, it would be nice to
be a list by default if somebody tries to `%Struct{}`.

Closes the issue:

https://github.com/tony612/protobuf-elixir/issues/93

### CODE REVIEW

**Comment by whatyouhide** [comment]
@ulissesalmeida one year later, almost to the day! :) Can you rebase this on the master branch? It's looking good to me 👍

**Comment by ulissesalmeida** [comment]
@whatyouhide I don't work anymore for Coingaming so I don't have access to fork repo anymore. haha 🙈 
I can't rebase this branch. I would have to open a new PR.

Maybe @thalesflores or @tkachuc-labs can help with the rebase.
If not, I can fork to my personal account and open a new PR.

**Comment by ulissesalmeida** [comment]
Thanks @thalesflores ❤️

**Comment by whatyouhide** [comment]
@thalesflores tests are failing locally for me 🤔 

```
  1) test generate/2 json_name is omitted when syntax is not proto3 (Protobuf.Protoc.Generator.MessageTest)
     test/protobuf/protoc/generator/message_test.exs:496
     Assertion with =~ failed
     code:  assert msg =~ "defstruct [:the_field_name]\n"
     left:  "defmodule Foo do\n  @moduledoc false\n  use Protobuf\n  @type t :: %__MODULE__{\n    the_field_name: String.t\n  }\n\n  defstruct [the_field_name: nil]\n\n\n  field :the_field_name, 1, required: true, type: :string\n\n\nend\n"
     right: "defstruct [:the_field_name]\n"
     stacktrace:
       test/protobuf/protoc/generator/message_test.exs:514: (test)

.

  2) test generate/2 json_name is added when it differs from the original field name (Protobuf.Protoc.Generator.MessageTest)
     test/protobuf/protoc/generator/message_test.exs:466
     Assertion with =~ failed
     code:  assert msg =~ "defstruct [:simple, :the_field_name]\n"
     left:  "defmodule Foo do\n  @moduledoc false\n  use Protobuf, syntax: :proto3\n  @type t :: %__MODULE__{\n    simple:         integer,\n    the_field_name: String.t\n  }\n\n  defstruct [simple: 0, the_field_name: \"\"]\n\n\n  field :simple, 1, type: :int32\n  field :the_field_name, 2, type: :string, json_name: \"theFieldName\"\n\n\nend\n"
     right: "defstruct [:simple, :the_field_name]\n"
     stacktrace:
       test/protobuf/protoc/generator/message_test.exs:491: (test)
```

**Comment by whatyouhide** [comment]
Closing in favor of #184 (see description there).

**Pull request closed without merging**
