### PR TITLE
Fix generation of message module with lowercase name

### PR DESCRIPTION
**Pull request by jeanparpaillon**
Fixes https://github.com/elixir-protobuf/protobuf/issues/250

### CODE REVIEW

**Comment by ericmj** [comment]
Thanks for the issue and PR. Can you add a test as well? Let us know if you need any pointers.

**Comment by jeanparpaillon** [comment]
@ericmj you're welcome
I would be glad to add a test but I am a little bit confused about the structure to generate for testing, like the ones in https://github.com/elixir-protobuf/protobuf/blob/main/test/protobuf/protoc/generator_test.exs#L48 for instance

**Comment by ericmj** [comment]
You can add a unit test here: https://github.com/elixir-protobuf/protobuf/blob/main/test/protobuf/protoc/generator/util_test.exs#L8-L31.

**Comment by jeanparpaillon** [comment]
@ericmj thanks for the hint. I've just added a test

**Comment by jeanparpaillon** [comment]
@whatyouhide you're welcome!

**Pull request merged**
